name: test_pages
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc
    - name: Install dependencies
      run: pip install '.[docs]'
    - name: Generate notebooks
      run: python docs/generate_example_notebooks.py
    - name: Build and Commit
      uses: waltsims/pages@pyproject.toml-support
